-- Sample tickets. Spring Boot runs this file on every startup (after Hibernate creates the table),
-- but the WHERE NOT EXISTS clause means rows are only inserted while the tickets table is empty,
-- so restarting the application does not create duplicates.
-- ids are generated by the database, so they are not listed here.
-- Standard SQL (INTERVAL '1' DAY) so it works on PostgreSQL and on the H2 database used by the tests.
INSERT INTO tickets (title, description, priority, status, created_by, created_at, updated_at)
SELECT title, description, priority, status, created_by, created_at, updated_at
FROM (VALUES
    ('Cannot log in to customer portal', 'Users report "invalid session" errors after entering correct credentials since this morning.', 'HIGH', 'OPEN', 'alice', CURRENT_TIMESTAMP - INTERVAL '1' DAY, CURRENT_TIMESTAMP - INTERVAL '1' DAY),
    ('Invoice PDF shows wrong currency', 'Invoices for EU customers display USD instead of EUR.', 'MEDIUM', 'IN_PROGRESS', 'bob', CURRENT_TIMESTAMP - INTERVAL '3' DAY, CURRENT_TIMESTAMP - INTERVAL '2' DAY),
    ('Add dark mode to dashboard', 'Several customers have requested a dark theme for the admin dashboard.', 'LOW', 'OPEN', 'carol', CURRENT_TIMESTAMP - INTERVAL '7' DAY, CURRENT_TIMESTAMP - INTERVAL '7' DAY),
    ('Password reset email not received', 'Reset emails are not arriving for addresses on the example.org domain.', 'HIGH', 'RESOLVED', 'dave', CURRENT_TIMESTAMP - INTERVAL '10' DAY, CURRENT_TIMESTAMP - INTERVAL '8' DAY),
    ('Search results load slowly', 'Searching orders takes over 10 seconds when more than 1,000 results match.', 'MEDIUM', 'OPEN', 'alice', CURRENT_TIMESTAMP - INTERVAL '2' DAY, CURRENT_TIMESTAMP - INTERVAL '2' DAY),
    ('Typo on pricing page', 'The word "subscription" is misspelled in the Pro plan description.', 'LOW', 'RESOLVED', 'erin', CURRENT_TIMESTAMP - INTERVAL '14' DAY, CURRENT_TIMESTAMP - INTERVAL '13' DAY),
    ('Mobile app crashes on startup', 'Android app version 3.2 crashes immediately on launch for some devices.', 'HIGH', 'IN_PROGRESS', 'frank', CURRENT_TIMESTAMP - INTERVAL '6' HOUR, CURRENT_TIMESTAMP - INTERVAL '2' HOUR),
    ('Export to CSV missing columns', 'The ticket export does not include the priority and status columns.', 'MEDIUM', 'OPEN', 'bob', CURRENT_TIMESTAMP - INTERVAL '4' DAY, CURRENT_TIMESTAMP - INTERVAL '4' DAY)
) AS seed (title, description, priority, status, created_by, created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM tickets);
